Import needed packages 
```{r}
library(ggplot2)
library(RColorBrewer)
library(dplyr)
```

Set colors for data
```{r}
# # From https://stackoverflow.com/questions/15282580/how-to-generate-a-number-of-most-distinctive-colors-in-r
qual_col_pals = brewer.pal.info[brewer.pal.info$category == 'qual',]
Color = unlist(mapply(brewer.pal, qual_col_pals$maxcolors, rownames(qual_col_pals)))
```


Read data 
```{r}
data <- read.table(file = "biotype_counts_processed.txt", sep = "\t", header = TRUE)
```

Change column names
```{r}
colnames(data) <- c("Biotype",
                    "Neuropil_Poly_1", "Neuropil_Poly_2", "Neuropil_Poly_3",
                    "Somata_Poly_1", "Somata_Poly_2", "Somata_Poly_3")


# Transforming the data
data_for_plot <- tidyr::gather(data, "Condition", "Reads", 2:7)
```


```{r}
sample_order <- c("Biotype",
                  "Neuropil_Poly_1", "Neuropil_Poly_2", "Neuropil_Poly_3",
                  "Somata_Poly_1", "Somata_Poly_2", "Somata_Poly_3")
```



```{r}
# Plot
pdf("CDS_biotypes.pdf", paper = "a4", useDingbats = FALSE)
ggplot(data_for_plot, 
       aes(x = factor(Condition, levels = sample_order),
           y = Reads,
           fill = Biotype)) + 
  geom_bar(position = "fill",
           stat = "identity",
           color = "black") +
  scale_fill_manual(values = Color) +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 90)) +
  xlab("") +
  ylab("Proportion of mapped reads")
dev.off()
```

